ci:
  autofix_prs: true
  autoupdate_schedule: weekly
  autoupdate_commit_msg: "chore: pre-commit autoupdate"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: "23.3.0"
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: "5.11.5"
    hooks:
      - id: isort

  - repo: local
    hooks:
      - id: make-clean-notebooks
        name: make-clean-notebooks
        entry: make clean-notebooks
        language: system
        pass_filenames: false
