name: edgewalker
channels:
  - conda-forge
dependencies:
  # Note, python 3.9 used locally, but Glue jobs only supports 3.6.  Anyway,
  # many of the libs are added for type hinting etc., so don't need to match
  # exactly.
  - python=3.9
  - pip
  - poetry
